# Generated by Django 3.2.23 on 2023-11-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('time', models.TimeField(auto_now=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
